r"""
This file has been automatically generated by sasfit_convert and manually edited
by Wojciech Potrzebowski, ESS on 2017-12-05.

The model calculates an empirical functional form for SAS data characterized
by broad_peak

Definition:
-----------
Many SANS spectra are characterized by a broad peak even though they are
from amorphous soft materials.
The d-spacing corresponding to the broad peak is a characteristic distance
between the scattering inhomogeneities (such as in lamellar, cylindrical,
or spherical morphologies or for bicontinuous structures).
The following simple functional form reproduces the broad peak feature:

.. math:: I(q) = \frac{I_0}{({1 + (|q - q_0|\xi)^m})}^p

Here the peak position is related to the d-spacing as $q0 = 2π/d$.
Soft systems that show a SANS peak include copolymers, polyelectrolytes,
multiphase systems, layered structures, etc.

..note::
    For $q0 = 0$, $m = 2$ and $p = 1$ one gets the Ornstein-Zernike model.
    For $q0 = 0$, $m = 2$ and $p = 2$ The Broad-Peak model is identical to the
    Debye-Anderson-Brumberger model.

For 2D data the scattering intensity is calculated in the same way as 1D,
where the $q$ vector is defined as

.. math:: q = \sqrt{q_x^2 + q_y^2}
References:
-----------

"""
from numpy import inf

name = "broad_peak"
title = " "
description = """F^2(q,I0,xi,m,q0) = I0/(1+(|q-q0|*xi)^m)^p
              List of default parameters
              I0: forward scattering
              xi: correlation length
              q0:peak position which is related to the d-spacing as q0 = 2pi/d
              m: exponent m
              p: exponnet p
              """
category = " "
#pylint: disable=bad-whitespace, line-too-long
parameters = [
 [ "I0", 	"", 	10.0, 	[-inf, inf], 	"", 	"I0: forward scattering"],
 [ "XI", 	"Ang", 	0.0, 	[-inf, inf], 	"", 	"xi: correlation length"],
 [ "Q0", 	"1/Ang", 	0.0, 	[-inf, inf], 	"", 	"q0:peak position which is related to the d-spacing as q0 = 2pi/d"],
 [ "M", 	"", 	2.0, 	[-inf, inf], 	"", 	"m: exponent m"],
 [ "P", 	"", 	1.0, 	[-inf, inf], 	"", 	"p: exponnet p"],
]
 #pylint: enable=bad-whitespace, line-too-long

source = ["sasfit_broad_peak.c"]

demo = dict(
	I0 = 10.0,
	XI = 0.0,
	Q0 = 0.0,
	M = 1.0,
	P = 0.0)
